name: jupyter
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - nbgitpuller
  - pandas
  - geopandas
  - notebook
  - python-snappy
  - numpy
  - beautifulsoup4
  - geopy
  - spacy==2.1.8
  - scikit-image==0.15.0
  - tensorflow==1.15.0
  - ipyleaflet
  - pip
  - pip:
    - facebook-scraper
    - fastai==1.0.60
    - arcgis==1.8.3
    - json-lines
    - git+https://www.github.com/keras-team/keras-contrib.git
    - neurotpr
