name: gogetit
on: [push]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Download
      uses: actions/checkout@v2
      with:
        repository: geoai-lab/neurotpr
        path: './NeuroTPR'
    - uses: EndBug/add-and-commit@v7.0.0 # commit keys as txt file to repo
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        add: ./NeuroTPR/PretrainedModel
