name: gogetit
on: [push]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Copy from repo
      uses: actions/checkout@v2
      with:
        repository: geoai-lab/neurotpr
        path: './NeuroTPR/'
    - run: cp -r ./NeuroTPR/PretrainedModel ./ 
    - uses: EndBug/add-and-commit@v7.0.0
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        add: 'dummy.*'
